ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "receiptFileName" VARCHAR(180);
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "receiptFileMimeType" VARCHAR(100);
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "receiptFileData" BYTEA;
