import { Router } from 'express';
import multer from 'multer';
import { mkdir, unlink } from 'node:fs/promises';
import { createReadStream } from 'node:fs';
import path from 'node:path';
import { randomUUID } from 'node:crypto';
import { z } from 'zod';
import { prisma } from '../lib/prisma.js';
import { authenticate, type AuthRequest } from '../middleware/auth.js';
import { AppError } from '../utils/errors.js';

export const bookingRouter = Router();
const schema = z.object({ customerId: z.string().uuid(), propertyId: z.string().uuid(), leadId: z.string().uuid().optional().nullable(), bookingDate: z.coerce.date(), bookingAmount: z.coerce.number().positive(), totalPropertyAmount: z.coerce.number().positive(), isOnlineBooking: z.boolean().optional().default(false) });
const tokenSchema = z.object({ tokenPaidAmount: z.coerce.number().min(0) });
const cancellationSchema = z.object({ reason: z.string().trim().min(5).max(1000) });
const uploadDirectory = path.resolve(process.cwd(), 'uploads', 'booking-documents');
const allowedTypes = new Set(['application/pdf', 'image/jpeg', 'image/png', 'image/webp']);
const extension = (mimeType: string) => ({ 'application/pdf': '.pdf', 'image/jpeg': '.jpg', 'image/png': '.png', 'image/webp': '.webp' }[mimeType] ?? '');
const storage = multer.diskStorage({ destination: async (_req, _file, cb) => { try { await mkdir(uploadDirectory, { recursive: true }); cb(null, uploadDirectory); } catch (error) { cb(error as Error, uploadDirectory); } }, filename: (_req, file, cb) => cb(null, `${randomUUID()}${extension(file.mimetype)}`) });
const upload = multer({ storage, limits: { fileSize: 8 * 1024 * 1024, files: 1 }, fileFilter: (_req, file, cb) => cb(null, allowedTypes.has(file.mimetype)) });
const bookingInclude = { customer: true, property: { include: { project: true } }, payments: true, documents: { select: { id: true, documentType: true, originalName: true, createdAt: true } } } as const;

bookingRouter.get('/documents/shared/:token', async (req, res, next) => { try { const token = z.string().uuid().parse(req.params.token); const document = await prisma.bookingDocument.findFirst({ where: { shareToken: token, shareExpiresAt: { gt: new Date() } } }); if (!document || !path.resolve(document.storagePath).startsWith(uploadDirectory + path.sep)) throw new AppError(404, 'SHARE_NOT_FOUND', 'This document share link has expired or is unavailable'); res.setHeader('Content-Type', document.mimeType); res.setHeader('Content-Disposition', `inline; filename="${document.originalName.replaceAll('"', '')}"`); createReadStream(document.storagePath).on('error', next).pipe(res); } catch (error) { next(error); } });

bookingRouter.use(authenticate);
bookingRouter.get('/', async (_req, res, next) => { try { const data = await prisma.booking.findMany({ include: bookingInclude, orderBy: { createdAt: 'desc' } }); res.json({ success: true, data }); } catch (error) { next(error); } });
bookingRouter.get('/documents/registry', async (_req, res, next) => { try { const data = await prisma.bookingDocument.findMany({ include: { booking: { include: { customer: true, property: { include: { project: true } } } } }, orderBy: { createdAt: 'desc' } }); res.json({ success: true, data }); } catch (error) { next(error); } });
bookingRouter.post('/', async (req: AuthRequest, res, next) => { try { const input = schema.parse(req.body); const data = await prisma.$transaction(async tx => { const customer = await tx.customer.findFirst({ where: { id: input.customerId, deletedAt: null } }); if (!customer) throw new AppError(422, 'INVALID_CUSTOMER', 'Select an active customer'); const reserved = await tx.property.updateMany({ where: { id: input.propertyId, deletedAt: null, status: 'AVAILABLE' }, data: { status: 'RESERVED' } }); if (reserved.count !== 1) throw new AppError(409, 'UNIT_UNAVAILABLE', 'This unit is no longer available for booking'); const created = await tx.booking.create({ data: { referenceNumber: `BKG-${Date.now()}-${Math.floor(Math.random() * 900 + 100)}`, customerId: input.customerId, propertyId: input.propertyId, leadId: input.leadId || null, bookingDate: input.bookingDate, bookingAmount: input.bookingAmount, totalPropertyAmount: input.totalPropertyAmount, isOnlineBooking: input.isOnlineBooking, status: 'PENDING_APPROVAL' }, include: bookingInclude }); await tx.auditLog.create({ data: { userId: req.auth!.userId, action: 'CREATE', entityType: 'BOOKING', entityId: created.id, newValues: { referenceNumber: created.referenceNumber, propertyId: created.propertyId, isOnlineBooking: created.isOnlineBooking, tokenAmount: input.bookingAmount } } }); return created; }); res.status(201).json({ success: true, data }); } catch (error) { next(error); } });
bookingRouter.patch('/:id/token', async (req: AuthRequest, res, next) => { try { const input = tokenSchema.parse(req.body); const id = z.string().uuid().parse(req.params.id); const booking = await prisma.booking.findUnique({ where: { id } }); if (!booking || booking.status === 'CANCELLED') throw new AppError(404, 'BOOKING_NOT_FOUND', 'Active booking not found'); if (input.tokenPaidAmount > Number(booking.bookingAmount)) throw new AppError(422, 'INVALID_TOKEN_AMOUNT', 'Token received cannot exceed the booked token amount'); const data = await prisma.booking.update({ where: { id }, data: { tokenPaidAmount: input.tokenPaidAmount }, include: bookingInclude }); await prisma.auditLog.create({ data: { userId: req.auth!.userId, action: 'UPDATE', entityType: 'BOOKING_TOKEN', entityId: id, oldValues: { tokenPaidAmount: booking.tokenPaidAmount }, newValues: input } }); res.json({ success: true, data }); } catch (error) { next(error); } });
bookingRouter.post('/:id/documents', upload.single('file'), async (req: AuthRequest, res, next) => { let stored: Express.Multer.File | undefined; try { stored = req.file; const bookingId = z.string().uuid().parse(req.params.id); const documentType = z.string().trim().min(2).max(40).parse(req.body.documentType || 'BOOKING_DOCUMENT'); if (!stored) throw new AppError(422, 'FILE_REQUIRED', 'Select a PDF or image to upload'); const booking = await prisma.booking.findUnique({ where: { id: bookingId } }); if (!booking) throw new AppError(404, 'BOOKING_NOT_FOUND', 'Booking not found'); const data = await prisma.bookingDocument.create({ data: { bookingId, documentType, originalName: path.basename(stored.originalname).slice(0, 180), storagePath: stored.path, mimeType: stored.mimetype, fileSize: stored.size, uploadedById: req.auth!.userId } }); await prisma.auditLog.create({ data: { userId: req.auth!.userId, action: 'UPLOAD_DOCUMENT', entityType: 'BOOKING_DOCUMENT', entityId: data.id, newValues: { bookingId, documentType } } }); res.status(201).json({ success: true, data: { id: data.id, originalName: data.originalName, documentType: data.documentType } }); } catch (error) { if (stored) await unlink(stored.path).catch(() => undefined); next(error); } });
bookingRouter.get('/documents/:documentId/download', async (req, res, next) => { try { const id = z.string().uuid().parse(req.params.documentId); const document = await prisma.bookingDocument.findUnique({ where: { id } }); if (!document || !path.resolve(document.storagePath).startsWith(uploadDirectory + path.sep)) throw new AppError(404, 'DOCUMENT_NOT_FOUND', 'Booking document not found'); res.setHeader('Content-Type', document.mimeType); res.setHeader('Content-Disposition', `attachment; filename="${document.originalName.replaceAll('"', '')}"`); createReadStream(document.storagePath).on('error', next).pipe(res); } catch (error) { next(error); } });
bookingRouter.patch('/documents/:documentId/signature', async (req: AuthRequest, res, next) => { try { const id = z.string().uuid().parse(req.params.documentId); const input = z.object({ signedByName: z.string().trim().min(2).max(160) }).parse(req.body); const document = await prisma.bookingDocument.update({ where: { id }, data: { signatureStatus: 'SIGNED', signedByName: input.signedByName, signedAt: new Date() } }); await prisma.auditLog.create({ data: { userId: req.auth!.userId, action: 'DIGITAL_SIGNATURE', entityType: 'BOOKING_DOCUMENT', entityId: id, newValues: { signedByName: input.signedByName } } }); res.json({ success: true, data: document }); } catch (error) { next(error); } });
bookingRouter.post('/documents/:documentId/share', async (req: AuthRequest, res, next) => { try { const id = z.string().uuid().parse(req.params.documentId); const document = await prisma.bookingDocument.findUnique({ where: { id } }); if (!document) throw new AppError(404, 'DOCUMENT_NOT_FOUND', 'Booking document not found'); const token = randomUUID(); const expiresAt = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000); await prisma.bookingDocument.update({ where: { id }, data: { shareToken: token, shareExpiresAt: expiresAt } }); await prisma.auditLog.create({ data: { userId: req.auth!.userId, action: 'CREATE_DOCUMENT_SHARE', entityType: 'BOOKING_DOCUMENT', entityId: id, newValues: { expiresAt } } }); res.json({ success: true, data: { shareUrl: `${req.protocol}://${req.get('host')}/api/v1/bookings/documents/shared/${token}`, expiresAt } }); } catch (error) { next(error); } });
bookingRouter.post('/:id/cancel', async (req: AuthRequest, res, next) => { try { if (!req.auth!.roles.some(role => ['ADMINISTRATOR', 'MANAGER'].includes(role))) throw new AppError(403, 'FORBIDDEN', 'Only an administrator or manager can cancel a booking'); const input = cancellationSchema.parse(req.body); const id = z.string().uuid().parse(req.params.id); const data = await prisma.$transaction(async tx => { const booking = await tx.booking.findUnique({ where: { id } }); if (!booking || booking.status === 'CANCELLED') throw new AppError(422, 'INVALID_BOOKING', 'Booking is already cancelled or unavailable'); await tx.property.update({ where: { id: booking.propertyId }, data: { status: 'AVAILABLE' } }); const cancelled = await tx.booking.update({ where: { id }, data: { status: 'CANCELLED', cancellationReason: input.reason, cancelledAt: new Date(), cancelledById: req.auth!.userId }, include: bookingInclude }); await tx.auditLog.create({ data: { userId: req.auth!.userId, action: 'CANCEL', entityType: 'BOOKING', entityId: id, oldValues: { status: booking.status }, newValues: { reason: input.reason } } }); return cancelled; }); res.json({ success: true, data }); } catch (error) { next(error); } });
