import { Router } from 'express';
import { z } from 'zod';
import { prisma } from '../lib/prisma.js';
import { authenticate, authorize, type AuthRequest } from '../middleware/auth.js';

export const loanRouter = Router();
const loanInput = z.object({ customerId: z.string().uuid(), bookingId: z.string().uuid().optional().nullable(), bankName: z.string().trim().min(2).max(160), branchName: z.string().trim().max(160).optional().nullable(), loanAccountNumber: z.string().trim().max(80).optional().nullable(), sanctionedAmount: z.coerce.number().positive(), interestRate: z.coerce.number().min(0).max(99).default(0), tenureMonths: z.coerce.number().int().min(1).max(600).optional().nullable(), emiAmount: z.coerce.number().min(0).default(0), status: z.enum(['APPLIED', 'SANCTIONED', 'PARTIALLY_DISBURSED', 'DISBURSED', 'CLOSED', 'REJECTED']).default('APPLIED'), notes: z.string().trim().max(1000).optional().nullable() });
loanRouter.use(authenticate, authorize('ADMINISTRATOR', 'MANAGER'));
loanRouter.get('/', async (_req, res, next) => { try { const [loans, customers, bookings] = await Promise.all([prisma.loan.findMany({ include: { customer: true, booking: { include: { property: { include: { project: true } } } }, disbursements: { orderBy: { disbursedAt: 'desc' } }, emis: { orderBy: { installment: 'asc' } } }, orderBy: { createdAt: 'desc' } }), prisma.customer.findMany({ where: { deletedAt: null }, orderBy: { fullName: 'asc' } }), prisma.booking.findMany({ include: { customer: true, property: { include: { project: true } } }, orderBy: { createdAt: 'desc' } })]); res.json({ success: true, data: { loans, customers, bookings } }); } catch (error) { next(error); } });
loanRouter.post('/', async (req: AuthRequest, res, next) => { try { const data = loanInput.parse(req.body); const count = await prisma.loan.count(); const loan = await prisma.loan.create({ data: { ...data, referenceNumber: `LOAN-${String(count + 1).padStart(5, '0')}`, sanctionedAt: data.status === 'SANCTIONED' ? new Date() : null } }); await prisma.auditLog.create({ data: { userId: req.auth!.userId, action: 'CREATE', entityType: 'LOAN', entityId: loan.id, newValues: data } }); res.status(201).json({ success: true, data: loan }); } catch (error) { next(error); } });
loanRouter.post('/:id/disbursements', async (req: AuthRequest, res, next) => { try { const loanId = z.string().uuid().parse(req.params.id); const data = z.object({ amount: z.coerce.number().positive(), disbursedAt: z.coerce.date(), reference: z.string().trim().max(120).optional().nullable(), notes: z.string().trim().max(1000).optional().nullable() }).parse(req.body); const result = await prisma.$transaction(async tx => { const item = await tx.loanDisbursement.create({ data: { ...data, loanId } }); const total = await tx.loanDisbursement.aggregate({ where: { loanId }, _sum: { amount: true } }); const loan = await tx.loan.findUniqueOrThrow({ where: { id: loanId } }); await tx.loan.update({ where: { id: loanId }, data: { disbursedAmount: total._sum.amount ?? 0, status: Number(total._sum.amount ?? 0) >= Number(loan.sanctionedAmount) ? 'DISBURSED' : 'PARTIALLY_DISBURSED' } }); return item; }); res.status(201).json({ success: true, data: result }); } catch (error) { next(error); } });
loanRouter.post('/:id/emis', async (req: AuthRequest, res, next) => { try { const loanId = z.string().uuid().parse(req.params.id); const data = z.object({ installment: z.coerce.number().int().min(1), dueDate: z.coerce.date(), amount: z.coerce.number().positive() }).parse(req.body); const result = await prisma.loanEmi.create({ data: { ...data, loanId } }); await prisma.auditLog.create({ data: { userId: req.auth!.userId, action: 'CREATE', entityType: 'LOAN_EMI', entityId: result.id, newValues: data } }); res.status(201).json({ success: true, data: result }); } catch (error) { next(error); } });
loanRouter.patch('/emis/:id/pay', async (req: AuthRequest, res, next) => { try { const id = z.string().uuid().parse(req.params.id); const paid = z.object({ amount: z.coerce.number().positive() }).parse(req.body).amount; const emi = await prisma.loanEmi.findUniqueOrThrow({ where: { id } }); const paidAmount = Number(emi.paidAmount) + paid; const data = await prisma.loanEmi.update({ where: { id }, data: { paidAmount, paidAt: new Date(), status: paidAmount >= Number(emi.amount) ? 'PAID' : 'PARTIAL' } }); await prisma.auditLog.create({ data: { userId: req.auth!.userId, action: 'UPDATE', entityType: 'LOAN_EMI', entityId: id, newValues: { paid } } }); res.json({ success: true, data }); } catch (error) { next(error); } });
