import { Router } from 'express';
import { z } from 'zod';
import { prisma } from '../lib/prisma.js';
import { authenticate, authorize, type AuthRequest } from '../middleware/auth.js';

export const settingsRouter = Router();
const profileSchema = z.object({ companyName: z.string().trim().min(2).max(120), address: z.string().trim().max(500).optional().or(z.literal('')), phone: z.string().trim().max(30).optional().or(z.literal('')), email: z.string().email().optional().or(z.literal('')), gstNumber: z.string().trim().max(40).optional().or(z.literal('')) });
const nameSchema = z.object({ name: z.string().trim().min(2).max(80) });
settingsRouter.use(authenticate, authorize('ADMINISTRATOR'));
settingsRouter.get('/', async (_req, res, next) => { try { const [company, departments, leadSources, roles] = await prisma.$transaction([prisma.companyProfile.findFirst(), prisma.department.findMany({ orderBy: { name: 'asc' } }), prisma.leadSource.findMany({ orderBy: { name: 'asc' } }), prisma.role.findMany({ include: { permissions: { include: { permission: true } } }, orderBy: { name: 'asc' } })]); res.json({ success: true, data: { company, departments, leadSources, roles: roles.map((role) => ({ id: role.id, code: role.code, name: role.name, permissions: role.permissions.map((item) => item.permission.code) })) } }); } catch (error) { next(error); } });
settingsRouter.put('/company', async (req: AuthRequest, res, next) => { try { const data = profileSchema.parse(req.body); const current = await prisma.companyProfile.findFirst(); const company = current ? await prisma.companyProfile.update({ where: { id: current.id }, data: { ...data, address: data.address || null, phone: data.phone || null, email: data.email || null, gstNumber: data.gstNumber || null } }) : await prisma.companyProfile.create({ data: { ...data, address: data.address || null, phone: data.phone || null, email: data.email || null, gstNumber: data.gstNumber || null } }); await prisma.auditLog.create({ data: { userId: req.auth!.userId, action: 'UPDATE_COMPANY_SETTINGS', entityType: 'COMPANY_PROFILE', entityId: company.id } }); res.json({ success: true, data: company }); } catch (error) { next(error); } });
settingsRouter.post('/departments', async (req: AuthRequest, res, next) => { try { const input = nameSchema.parse(req.body); const data = await prisma.department.create({ data: input }); await prisma.auditLog.create({ data: { userId: req.auth!.userId, action: 'CREATE_DEPARTMENT', entityType: 'DEPARTMENT', entityId: data.id, newValues: input } }); res.status(201).json({ success: true, data }); } catch (error) { next(error); } });
settingsRouter.post('/lead-sources', async (req: AuthRequest, res, next) => { try { const input = nameSchema.parse(req.body); const data = await prisma.leadSource.create({ data: input }); await prisma.auditLog.create({ data: { userId: req.auth!.userId, action: 'CREATE_LEAD_SOURCE', entityType: 'LEAD_SOURCE', entityId: data.id, newValues: input } }); res.status(201).json({ success: true, data }); } catch (error) { next(error); } });
