import express from 'express';
import helmet from 'helmet';
import cors from 'cors';
import cookieParser from 'cookie-parser';
import rateLimit from 'express-rate-limit';
import { pinoHttp } from 'pino-http';
import { randomUUID } from 'node:crypto';
import { env } from './config/env.js';
import { brokerRouter } from './routes/broker.routes.js';
import { loanRouter } from './routes/loan.routes.js';
import { expenseRouter } from './routes/expense.routes.js';
import { approvalRouter } from './routes/approval.routes.js';
import { analyticsRouter } from './routes/analytics.routes.js';
import { authRouter } from './routes/auth.routes.js'; import { dashboardRouter } from './routes/dashboard.routes.js'; import { employeeRouter } from './routes/employee.routes.js'; import { attendanceRouter } from './routes/attendance.routes.js'; import { teamRouter } from './routes/team.routes.js'; import { securityRouter } from './routes/security.routes.js'; import { propertyRouter } from './routes/property.routes.js'; import { leadRouter } from './routes/lead.routes.js'; import { followUpRouter } from './routes/follow-up.routes.js'; import { siteVisitRouter } from './routes/site-visit.routes.js'; import { customerRouter } from './routes/customer.routes.js'; import { bookingRouter } from './routes/booking.routes.js'; import { paymentRouter } from './routes/payment.routes.js'; import { reportRouter } from './routes/report.routes.js'; import { exportRouter } from './routes/export.routes.js'; import { importRouter } from './routes/import.routes.js'; import { customerDocumentRouter } from './routes/customer-document.routes.js'; import { auditLogRouter } from './routes/audit-log.routes.js'; import { notificationRouter } from './routes/notification.routes.js'; import { settingsRouter } from './routes/settings.routes.js';
import { errorHandler } from './middleware/error-handler.js';
import { prisma } from './lib/prisma.js';

const officeOrigin = /^http:\/\/(localhost|127\.0\.0\.1|10\.\d{1,3}\.\d{1,3}\.\d{1,3}|192\.168\.\d{1,3}\.\d{1,3}|172\.(1[6-9]|2\d|3[0-1])\.\d{1,3}\.\d{1,3}):5173$/;
export const app = express();
const allowedOrigin = (origin?: string) => env.NODE_ENV === 'production' ? origin === env.WEB_ORIGIN : !origin || origin === env.WEB_ORIGIN || origin === 'https://erp.rrpl.local' || officeOrigin.test(origin);
app.set('trust proxy', 1); app.disable('x-powered-by'); app.disable('etag');
const allowedOfficeIps = env.OFFICE_ALLOWED_IPS.split(',').map((ip) => ip.trim()).filter(Boolean);
app.use((req, res, next) => { const ip = (req.ip || '').replace(/^::ffff:/, ''); if (allowedOfficeIps.length && !allowedOfficeIps.includes(ip) && ip !== '127.0.0.1' && ip !== '::1') return res.status(403).json({ success: false, error: { code: 'IP_RESTRICTED', message: 'This office network is not permitted to access the ERP.' } }); next(); });
app.use((req, res, next) => { res.setHeader('x-request-id', req.headers['x-request-id']?.toString() ?? randomUUID()); next(); });
app.use(pinoHttp({ redact: ['req.headers.authorization', 'req.headers.cookie', 'res.headers.set-cookie', 'req.headers.x-vercel-oidc-token', 'req.headers.x-vercel-proxy-signature', 'req.headers.forwarded'] }));
app.use(helmet({ crossOriginResourcePolicy: { policy: 'same-site' }, hsts: env.NODE_ENV === 'production' ? { maxAge: 31_536_000, includeSubDomains: true } : false }));
app.use(cors({ origin: (origin, callback) => callback(null, allowedOrigin(origin)), credentials: true, methods: ['GET', 'POST', 'PATCH', 'PUT', 'DELETE'] }));
app.use(rateLimit({ windowMs: 15 * 60_000, limit: 10_000, standardHeaders: true, legacyHeaders: false, skip: req => req.path === '/health', message: { success: false, error: { code: 'RATE_LIMITED', message: 'Too many requests. Please try again later.' } } }));
app.use(express.json({ limit: '1mb', type: 'application/json' })); app.use(cookieParser());
app.get('/health', async (_req, res, next) => { try { await prisma.$queryRaw`SELECT 1`; res.json({ success: true, data: { status: 'ok' } }); } catch (error) { next(error); } });
app.use('/api/v1/auth', authRouter); app.use('/api/v1/dashboard', dashboardRouter); app.use('/api/v1/employees', employeeRouter); app.use('/api/v1/attendance', attendanceRouter); app.use('/api/v1/team', teamRouter); app.use('/api/v1/security', securityRouter); app.use('/api/v1/brokers', brokerRouter); app.use('/api/v1/loans', loanRouter); app.use('/api/v1/expenses', expenseRouter); app.use('/api/v1/approvals', approvalRouter); app.use('/api/v1/properties', propertyRouter); app.use('/api/v1/leads', leadRouter); app.use('/api/v1/follow-ups', followUpRouter); app.use('/api/v1/site-visits', siteVisitRouter); app.use('/api/v1/customers', customerRouter); app.use('/api/v1/bookings', bookingRouter); app.use('/api/v1/payments', paymentRouter); app.use('/api/v1/reports', reportRouter); app.use('/api/v1/exports', exportRouter); app.use('/api/v1/imports', importRouter); app.use('/api/v1/customer-documents', customerDocumentRouter); app.use('/api/v1/audit-logs', auditLogRouter); app.use('/api/v1/notifications', notificationRouter); app.use('/api/v1/settings', settingsRouter);
app.use('/api/v1/analytics', analyticsRouter);
app.use((_req, res) => res.status(404).json({ success: false, error: { code: 'NOT_FOUND', message: 'Route not found' } }));
app.use(errorHandler);
