import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { History } from 'lucide-react';
import { api } from '../lib/api';

type Activity = { id: string; action: string; entityType: string; oldValues: unknown; newValues: unknown; createdAt: string; actor: string };
const types = ['', 'LEAD', 'PROPERTY', 'BOOKING', 'PAYMENT', 'CUSTOMER', 'CUSTOMER_DOCUMENT'];
const label = (text: string) => text.split('_').map((word) => word[0] + word.slice(1).toLowerCase()).join(' ');
function summary(item: Activity) { const values = (item.newValues ?? item.oldValues) as Record<string, unknown> | null; return values && typeof values === 'object' ? Object.entries(values).slice(0, 3).map(([key, value]) => `${label(key)}: ${String(value)}`).join(' · ') || 'Record activity recorded.' : 'Record activity recorded.'; }
export function ActivityHistoryPage() { const [entityType, setEntityType] = useState(''); const { data = [], isLoading } = useQuery({ queryKey: ['audit-logs', entityType], queryFn: async () => (await api.get<{ data: Activity[] }>('/audit-logs', { params: { entityType: entityType || undefined } })).data.data }); return <section><p className="text-sm text-slate-500">Administration / Activity history</p><div className="mt-2 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-bold text-navy">Activity history</h2><p className="mt-1 text-sm text-slate-600">See who changed leads, properties, bookings, payments, customers, and documents.</p></div><select value={entityType} onChange={(event) => setEntityType(event.target.value)} className="rounded border bg-white px-3 py-2 text-sm"><option value="">All records</option>{types.slice(1).map((type) => <option key={type} value={type}>{label(type)}</option>)}</select></div><div className="mt-6 overflow-hidden rounded-lg border bg-white">{isLoading ? <p className="p-6 text-sm text-slate-500">Loading activity history…</p> : data.length === 0 ? <div className="p-10 text-center"><History className="mx-auto text-slate-400" /><p className="mt-3 text-sm text-slate-500">No matching activity recorded yet.</p></div> : <table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-slate-50 text-slate-500"><tr><th className="p-4">When</th><th className="p-4">Changed by</th><th className="p-4">Record</th><th className="p-4">Action</th><th className="p-4">Details</th></tr></thead><tbody>{data.map((item) => <tr key={item.id} className="border-t align-top"><td className="whitespace-nowrap p-4 text-slate-600">{new Date(item.createdAt).toLocaleString()}</td><td className="p-4 font-medium text-navy">{item.actor}</td><td className="p-4">{label(item.entityType)}</td><td className="p-4">{label(item.action)}</td><td className="max-w-md p-4 text-slate-600">{summary(item)}</td></tr>)}</tbody></table>}</div></section>; }
