import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Clock3, LogIn, LogOut, Users } from 'lucide-react';
import { api } from '../lib/api';
import { useAuth } from '../contexts/auth-context';

type Attendance = { id: string; checkInAt: string; checkOutAt: string | null; notes: string | null; employee?: { fullName: string; employeeCode: string; department: string } };
const formatTime = (value?: string | null) => value ? new Date(value).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : '—';
const worked = (item?: Attendance | null) => item?.checkOutAt ? `${Math.max(0, Math.floor((new Date(item.checkOutAt).getTime() - new Date(item.checkInAt).getTime()) / 3_600_000))}h ${Math.floor(((new Date(item.checkOutAt).getTime() - new Date(item.checkInAt).getTime()) % 3_600_000) / 60_000)}m` : 'In progress';

export function AttendancePage() {
  const client = useQueryClient(); const { user } = useAuth(); const isManager = user?.roles.some(role => role === 'ADMINISTRATOR' || role === 'MANAGER') ?? false;
  const today = useQuery({ queryKey: ['attendance', 'today'], queryFn: async () => (await api.get<{ data: Attendance | null }>('/attendance/me/today')).data.data });
  const report = useQuery({ enabled: isManager, queryKey: ['attendance', 'report'], queryFn: async () => (await api.get<{ data: Attendance[] }>('/attendance')).data.data });
  const action = useMutation({ mutationFn: (path: 'check-in' | 'check-out') => api.post(`/attendance/me/${path}`, {}), onSuccess: () => { void client.invalidateQueries({ queryKey: ['attendance'] }); } });
  const record = today.data;
  return <section><p className="text-sm text-slate-500">Workspace / Attendance</p><div className="mt-2 flex items-center gap-3"><Clock3 className="text-gold" /><div><h2 className="text-2xl font-bold text-navy">My attendance</h2><p className="mt-1 text-sm text-slate-600">Mark your daily office check-in and check-out.</p></div></div>
    <div className="mt-6 rounded-xl border bg-white p-6 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="font-semibold text-navy">{new Date().toLocaleDateString(undefined, { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}</p><p className="mt-1 text-sm text-slate-500">{today.isLoading ? 'Loading attendance…' : !record ? 'Attendance not marked yet.' : record.checkOutAt ? `Completed · ${worked(record)}` : `Checked in at ${formatTime(record.checkInAt)}`}</p></div><div className="flex gap-3">{!record && <button disabled={action.isPending} onClick={() => action.mutate('check-in')} className="rounded bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50"><LogIn className="mr-2 inline" size={16} />Mark check-in</button>}{record && !record.checkOutAt && <button disabled={action.isPending} onClick={() => action.mutate('check-out')} className="rounded bg-navy px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50"><LogOut className="mr-2 inline" size={16} />Mark check-out</button>}</div></div>{action.isError && <p className="mt-4 rounded bg-red-50 p-3 text-sm text-red-700">Could not save attendance. Refresh and try again.</p>} {record && <div className="mt-5 grid gap-3 border-t pt-5 text-sm sm:grid-cols-3"><p><span className="text-slate-500">Check-in</span><br /><b>{formatTime(record.checkInAt)}</b></p><p><span className="text-slate-500">Check-out</span><br /><b>{formatTime(record.checkOutAt)}</b></p><p><span className="text-slate-500">Working time</span><br /><b>{worked(record)}</b></p></div>}</div>
    {isManager && <div className="mt-7 rounded-xl border bg-white"><div className="flex items-center gap-2 border-b p-5"><Users size={18} className="text-gold" /><h3 className="font-semibold text-navy">Today’s employee attendance</h3></div>{report.isLoading ? <p className="p-5 text-sm text-slate-500">Loading report…</p> : <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-slate-500"><tr><th className="p-4">Employee</th><th className="p-4">Department</th><th className="p-4">Check-in</th><th className="p-4">Check-out</th><th className="p-4">Working time</th></tr></thead><tbody>{(report.data ?? []).map(item => <tr key={item.id} className="border-t"><td className="p-4 font-medium">{item.employee?.fullName}<br /><span className="text-xs text-slate-500">{item.employee?.employeeCode}</span></td><td className="p-4">{item.employee?.department}</td><td className="p-4">{formatTime(item.checkInAt)}</td><td className="p-4">{formatTime(item.checkOutAt)}</td><td className="p-4">{worked(item)}</td></tr>)}{!report.data?.length && <tr><td colSpan={5} className="p-5 text-center text-slate-500">No attendance marked today.</td></tr>}</tbody></table></div>}</div>}</section>;
}
