import { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Building2, LockKeyhole } from 'lucide-react';
import { api } from '../lib/api';

type Status = 'AVAILABLE' | 'IN_DISCUSSION' | 'RESERVED' | 'BOOKED' | 'SOLD' | string;
type Property = { id: string; referenceNumber: string; unitNumber: string; type: string; finalPrice: string | number; status: Status; lockCustomerName?: string | null; lockExpiresAt?: string | null; project: { name: string; location?: string } };
const columns: { status: Status; title: string; tone: string }[] = [{ status: 'AVAILABLE', title: 'Available', tone: 'border-emerald-200 bg-emerald-50' }, { status: 'IN_DISCUSSION', title: 'In discussion', tone: 'border-amber-200 bg-amber-50' }, { status: 'RESERVED', title: 'Reserved', tone: 'border-blue-200 bg-blue-50' }, { status: 'BOOKED', title: 'Booked', tone: 'border-purple-200 bg-purple-50' }, { status: 'SOLD', title: 'Sold', tone: 'border-slate-300 bg-slate-100' }];

export function AvailabilityBoardPage() {
  const [project, setProject] = useState('');
  const { data = [], isLoading } = useQuery({ queryKey: ['properties'], queryFn: async () => (await api.get<{ data: Property[] }>('/properties')).data.data });
  const projects = useMemo(() => [...new Set(data.map((item) => item.project.name))].sort(), [data]);
  const visible = data.filter((item) => !project || item.project.name === project);
  return <section><p className="text-sm text-slate-500">Inventory / Availability board</p><div className="mt-2 flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-2xl font-bold text-navy">Property availability board</h2><p className="mt-1 text-sm text-slate-600">A live unit view for sales and inventory coordination.</p></div><label className="text-sm font-medium text-slate-700">Project<select value={project} onChange={(event) => setProject(event.target.value)} className="ml-2 rounded border bg-white px-3 py-2"><option value="">All projects</option>{projects.map((name) => <option key={name}>{name}</option>)}</select></label></div>{isLoading ? <p className="mt-6 rounded border bg-white p-6 text-sm text-slate-500">Loading availability…</p> : visible.length === 0 ? <div className="mt-6 rounded border bg-white p-10 text-center"><Building2 className="mx-auto text-slate-400" /><p className="mt-3 text-sm text-slate-500">No property units match this view.</p></div> : <div className="mt-6 grid gap-4 xl:grid-cols-5">{columns.map((column) => { const units = visible.filter((item) => item.status === column.status); return <div key={column.status} className={`min-h-72 rounded-lg border p-3 ${column.tone}`}><div className="flex items-center justify-between"><h3 className="font-semibold text-navy">{column.title}</h3><span className="rounded bg-white px-2 py-1 text-xs font-medium text-slate-700">{units.length}</span></div><div className="mt-3 space-y-3">{units.length === 0 ? <p className="rounded bg-white/70 p-3 text-xs text-slate-500">No units</p> : units.map((unit) => <article key={unit.id} className="rounded border border-slate-200 bg-white p-3 shadow-sm"><div className="flex items-start justify-between gap-2"><div><p className="font-semibold text-navy">{unit.unitNumber}</p><p className="text-xs text-slate-500">{unit.project.name}</p></div><span className="text-xs text-slate-500">{unit.type}</span></div><p className="mt-2 text-sm font-medium">₹{Number(unit.finalPrice).toLocaleString('en-IN')}</p>{unit.status === 'IN_DISCUSSION' && <p className="mt-2 flex items-center gap-1 text-xs text-amber-800"><LockKeyhole size={13} />{unit.lockCustomerName || 'Customer discussion'}{unit.lockExpiresAt ? ` until ${new Date(unit.lockExpiresAt).toLocaleDateString()}` : ''}</p>}<p className="mt-2 text-xs text-slate-400">{unit.referenceNumber}</p></article>)}</div></div>; })}</div>}</section>;
}
