import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { BadgeIndianRupee, Plus, ReceiptText, UsersRound } from 'lucide-react';
import { api } from '../lib/api';

type Broker = { id: string; code: string; fullName: string; companyName?: string | null; phone: string; email?: string | null; status: string; commissionRules: { id: string; rateType: string; rate: string | number; project?: { name: string } | null }[]; payouts: { id: string; amount: string | number; status: string; reference?: string | null; booking?: { referenceNumber: string; customer: { fullName: string }; property: { unitNumber: string; project: { name: string } } } | null }[] };
type Project = { id: string; name: string };
type Booking = { id: string; referenceNumber: string; customer: { fullName: string }; property: { unitNumber: string; project: { name: string } } };
type Data = { brokers: Broker[]; projects: Project[]; bookings: Booking[] };
const amount = (v: number | string) => `₹${Number(v).toLocaleString('en-IN')}`;

export function BrokersPage() {
  const client = useQueryClient(); const [message, setMessage] = useState(''); const [profileOpen, setProfileOpen] = useState(false); const [ruleOpen, setRuleOpen] = useState(false); const [payoutOpen, setPayoutOpen] = useState(false);
  const [profile, setProfile] = useState({ fullName: '', companyName: '', phone: '', email: '', reraNumber: '', panNumber: '', address: '' }); const [rule, setRule] = useState({ brokerId: '', projectId: '', rateType: 'PERCENTAGE', rate: '', notes: '' }); const [payout, setPayout] = useState({ brokerId: '', bookingId: '', amount: '', reference: '', notes: '' });
  const query = useQuery({ queryKey: ['brokers'], queryFn: async () => (await api.get<{ data: Data }>('/brokers')).data.data }); const data = query.data;
  const refresh = () => client.invalidateQueries({ queryKey: ['brokers'] }); const done = (text: string) => { refresh(); setMessage(text); };
  const createBroker = useMutation({ mutationFn: () => api.post('/brokers', profile), onSuccess: () => { setProfileOpen(false); setProfile({ fullName: '', companyName: '', phone: '', email: '', reraNumber: '', panNumber: '', address: '' }); done('Broker profile created.'); }, onError: () => setMessage('Could not create broker. Check required name, phone and email fields.') });
  const createRule = useMutation({ mutationFn: () => api.post('/brokers/rules', { ...rule, projectId: rule.projectId || null, rate: Number(rule.rate), notes: rule.notes || null }), onSuccess: () => { setRuleOpen(false); done('Commission rule saved.'); }, onError: () => setMessage('Could not save commission rule.') });
  const createPayout = useMutation({ mutationFn: () => api.post('/brokers/payouts', { ...payout, bookingId: payout.bookingId || null, amount: Number(payout.amount), reference: payout.reference || null, notes: payout.notes || null }), onSuccess: () => { setPayoutOpen(false); done('Broker payout added as pending.'); }, onError: () => setMessage('Could not add payout.') });
  const updatePayout = useMutation({ mutationFn: ({ id, status }: { id: string; status: string }) => api.patch(`/brokers/payouts/${id}`, { status }), onSuccess: () => done('Payout status updated.') });
  if (query.isLoading || !data) return <p className="text-slate-500">Loading brokers...</p>;
  const brokerOptions = <><option value="">Select broker</option>{data.brokers.map(b => <option key={b.id} value={b.id}>{b.fullName} · {b.code}</option>)}</>;
  return <section><p className="text-sm text-slate-500">Administration / Brokers</p><div className="mt-2 flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-2xl font-bold text-navy">Broker management</h2><p className="mt-1 text-sm text-slate-600">Broker profiles, commission rules, and payout tracking.</p></div><div className="flex flex-wrap gap-2"><button onClick={() => setRuleOpen(true)} className="rounded border border-navy px-3 py-2.5 text-sm text-navy"><BadgeIndianRupee className="mr-1 inline" size={16}/>Commission rule</button><button onClick={() => setPayoutOpen(true)} className="rounded border border-navy px-3 py-2.5 text-sm text-navy"><ReceiptText className="mr-1 inline" size={16}/>Add payout</button><button onClick={() => setProfileOpen(true)} className="rounded bg-navy px-4 py-2.5 text-sm text-white"><Plus className="mr-1 inline" size={16}/>Add broker</button></div></div>{message && <p className="mt-5 rounded bg-blue-50 p-3 text-sm text-navy">{message}</p>}
  {profileOpen && <form onSubmit={e => { e.preventDefault(); createBroker.mutate(); }} className="mt-6 rounded-lg border bg-white p-5"><h3 className="font-semibold">New broker profile</h3><div className="mt-4 grid gap-3 md:grid-cols-2">{[['fullName','Full name *'],['companyName','Company name'],['phone','Phone *'],['email','Email'],['reraNumber','RERA number'],['panNumber','PAN number'],['address','Address']].map(([key,label]) => <label className="text-sm font-medium" key={key}>{label}<input required={key === 'fullName' || key === 'phone'} value={profile[key as keyof typeof profile]} onChange={e => setProfile({ ...profile, [key]: e.target.value })} className="mt-1 w-full rounded border p-2.5" /></label>)}</div><button className="mt-4 rounded bg-navy px-4 py-2.5 text-sm text-white">Save broker</button></form>}
  {ruleOpen && <form onSubmit={e => { e.preventDefault(); createRule.mutate(); }} className="mt-6 rounded-lg border bg-white p-5"><h3 className="font-semibold">Commission rule</h3><div className="mt-4 grid gap-3 md:grid-cols-2"><select required value={rule.brokerId} onChange={e => setRule({ ...rule, brokerId: e.target.value })} className="rounded border p-2.5">{brokerOptions}</select><select value={rule.projectId} onChange={e => setRule({ ...rule, projectId: e.target.value })} className="rounded border p-2.5"><option value="">All projects</option>{data.projects.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select><select value={rule.rateType} onChange={e => setRule({ ...rule, rateType: e.target.value })} className="rounded border p-2.5"><option value="PERCENTAGE">Percentage (%)</option><option value="FIXED">Fixed amount (₹)</option></select><input required type="number" min="0.01" value={rule.rate} onChange={e => setRule({ ...rule, rate: e.target.value })} placeholder="Commission rate" className="rounded border p-2.5" /></div><button className="mt-4 rounded bg-navy px-4 py-2.5 text-sm text-white">Save rule</button></form>}
  {payoutOpen && <form onSubmit={e => { e.preventDefault(); createPayout.mutate(); }} className="mt-6 rounded-lg border bg-white p-5"><h3 className="font-semibold">Broker payout</h3><div className="mt-4 grid gap-3 md:grid-cols-2"><select required value={payout.brokerId} onChange={e => setPayout({ ...payout, brokerId: e.target.value })} className="rounded border p-2.5">{brokerOptions}</select><select value={payout.bookingId} onChange={e => setPayout({ ...payout, bookingId: e.target.value })} className="rounded border p-2.5"><option value="">No linked booking</option>{data.bookings.map(b => <option key={b.id} value={b.id}>{b.referenceNumber} · {b.customer.fullName} · {b.property.unitNumber}</option>)}</select><input required type="number" min="1" value={payout.amount} onChange={e => setPayout({ ...payout, amount: e.target.value })} placeholder="Payout amount" className="rounded border p-2.5" /><input value={payout.reference} onChange={e => setPayout({ ...payout, reference: e.target.value })} placeholder="Reference / cheque number" className="rounded border p-2.5" /></div><button className="mt-4 rounded bg-navy px-4 py-2.5 text-sm text-white">Save pending payout</button></form>}
  <div className="mt-6 overflow-x-auto rounded-lg border bg-white"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-slate-500"><tr><th className="p-4">Broker</th><th className="p-4">Contact</th><th className="p-4">Commission rules</th><th className="p-4">Payouts</th></tr></thead><tbody>{data.brokers.map(b => <tr className="border-t align-top" key={b.id}><td className="p-4"><b className="text-navy">{b.fullName}</b><span className="block text-xs text-slate-500">{b.code}{b.companyName ? ` · ${b.companyName}` : ''}</span></td><td className="p-4">{b.phone}<span className="block text-xs text-slate-500">{b.email || '—'}</span></td><td className="p-4">{b.commissionRules.length ? b.commissionRules.map(r => <p key={r.id}>{r.project?.name || 'All projects'}: <b>{r.rateType === 'PERCENTAGE' ? `${r.rate}%` : amount(r.rate)}</b></p>) : <span className="text-slate-400">No rule set</span>}</td><td className="p-4">{b.payouts.length ? b.payouts.map(p => <div className="mb-2" key={p.id}><b>{amount(p.amount)}</b> · <span className={p.status === 'PAID' ? 'text-emerald-700' : 'text-amber-700'}>{p.status}</span><span className="block text-xs text-slate-500">{p.booking ? `${p.booking.referenceNumber} · ${p.booking.customer.fullName}` : 'No booking linked'}</span>{p.status === 'PENDING' && <button onClick={() => updatePayout.mutate({ id: p.id, status: 'APPROVED' })} className="mt-1 text-xs text-navy underline">Approve</button>}{p.status === 'APPROVED' && <button onClick={() => updatePayout.mutate({ id: p.id, status: 'PAID' })} className="mt-1 text-xs text-emerald-700 underline">Mark paid</button>}</div>) : <span className="text-slate-400">No payouts</span>}</td></tr>)}</tbody></table>{!data.brokers.length && <div className="p-10 text-center text-slate-500"><UsersRound className="mx-auto"/><p className="mt-2">No brokers added yet.</p></div>}</div></section>;
}
