import { Building2, CalendarClock, Home, UserPlus, UserRoundPlus, Users } from 'lucide-react';
import { useQuery } from '@tanstack/react-query';
import { useNavigate } from 'react-router-dom';
import { api } from '../lib/api';
import { useAuth } from '../contexts/auth-context';

type Overview = { activeLeads: number; newLeadsToday: number; pendingFollowUps: number; availableProperties: number };
type DailyTask = { id: string; title: string; dueDate: string; priority: 'LOW' | 'MEDIUM' | 'HIGH'; status: 'PENDING' | 'IN_PROGRESS'; notes?: string | null };

export function DashboardPage() {
  const navigate = useNavigate(); const { user } = useAuth(); const isAdministrator = user?.roles.includes('ADMINISTRATOR') ?? false;
  const hour = new Date().getHours(); const greeting = hour < 12 ? 'Good morning' : hour < 17 ? 'Good afternoon' : 'Good evening';
  const overview = useQuery({ queryKey: ['dashboard', 'overview'], queryFn: async () => (await api.get<{ data: Overview }>('/dashboard/overview')).data.data, retry: 3, retryDelay: 1200, refetchOnWindowFocus: true });
  const attendance = useQuery({ enabled: !isAdministrator, queryKey: ['attendance', 'today'], queryFn: async () => (await api.get<{ data: { checkOutAt: string | null } | null }>('/attendance/me/today')).data.data });
  const tasks = useQuery({ enabled: !isAdministrator, queryKey: ['dashboard', 'my-tasks'], queryFn: async () => (await api.get<{ data: DailyTask[] }>('/dashboard/my-tasks')).data.data, refetchOnWindowFocus: true });
  const cards = [['Active leads', overview.data?.activeLeads, Users], ['New leads today', overview.data?.newLeadsToday, UserPlus], ['Pending follow-ups', overview.data?.pendingFollowUps, CalendarClock], ['Available properties', overview.data?.availableProperties, Home]] as const;
  const actions = [['Add lead', '/leads', UserPlus], ['Add property', '/properties', Building2], ['Schedule follow-up', '/follow-ups', CalendarClock], ...(isAdministrator ? [['Add employee', '/employees', UserRoundPlus] as const] : [])] as const;
  return <><div><p className="text-sm text-slate-500">Dashboard / Overview</p><h2 className="mt-1 text-2xl font-bold text-navy">{greeting}</h2><p className="mt-1 text-sm text-slate-600">A live view of your current operations.</p></div>
    {!isAdministrator && !attendance.isLoading && !attendance.data && <section className="mt-5 flex items-center justify-between rounded-lg border border-amber-200 bg-amber-50 p-4"><div><b className="text-navy">Attendance required</b><p className="mt-1 text-sm text-slate-600">Mark your check-in before starting today’s work.</p></div><button onClick={() => navigate('/attendance')} className="rounded bg-navy px-4 py-2 text-sm font-semibold text-white">Mark attendance</button></section>}
    {overview.isError && <p role="alert" className="mt-5 rounded bg-red-50 p-3 text-sm text-red-700">Dashboard data could not be loaded.</p>}<section className="mt-6 rounded-lg border bg-white p-5"><h3 className="font-semibold text-navy">Quick actions</h3><div className="mt-4 flex flex-wrap gap-3">{actions.map(([label, path, Icon]) => <button key={path} onClick={() => navigate(path)} className="flex items-center gap-2 rounded border border-slate-300 px-4 py-2 text-sm font-medium text-navy hover:bg-slate-50"><Icon size={17} />{label}</button>)}</div></section><section className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value, Icon]) => <article key={label} className="rounded-lg border bg-white p-5 shadow-sm"><Icon className="text-gold" size={22} /><p className="mt-5 text-sm text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold text-navy">{overview.isLoading ? '...' : value}</p></article>)}</section><section className="mt-7 rounded-lg border bg-white p-6"><div className="flex items-center justify-between gap-4"><div><h3 className="font-semibold text-navy">My tasks today</h3><p className="mt-1 text-sm text-slate-500">Tasks assigned by your manager are shown here.</p></div>{!isAdministrator && <button onClick={() => navigate('/notifications')} className="text-sm font-medium text-navy underline">View notifications</button>}</div>{isAdministrator ? <p className="mt-4 text-sm text-slate-500">Team tasks are managed from Team management.</p> : tasks.isLoading ? <p className="mt-4 text-sm text-slate-500">Loading assigned tasks...</p> : tasks.isError ? <p className="mt-4 text-sm text-red-700">Could not load assigned tasks. Refresh and try again.</p> : tasks.data?.length ? <div className="mt-4 grid gap-3 md:grid-cols-2">{tasks.data.map((task) => <article key={task.id} className="rounded border border-amber-200 bg-amber-50 p-4"><div className="flex items-start justify-between gap-3"><p className="font-medium text-navy">{task.title}</p><span className="rounded bg-white px-2 py-1 text-xs font-semibold text-slate-600">{task.priority}</span></div>{task.notes && <p className="mt-2 text-sm text-slate-600">{task.notes}</p>}<p className="mt-2 text-xs text-slate-500">Due {new Date(task.dueDate).toLocaleDateString('en-IN')}</p></article>)}</div> : <p className="mt-4 text-sm text-slate-500">No assigned tasks for today.</p>}</section></>;
}
