import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { CheckCircle2, Plus, Search, Users } from 'lucide-react';
import { api } from '../lib/api';

type Lead = { id: string; referenceNumber: string; customerName: string; primaryPhone: string; email: string | null; source: string; priority: string; status: string; assignedEmployee?: { fullName: string } | null };
const statuses = ['NEW', 'CONTACTED', 'INTERESTED', 'SITE_VISIT_SCHEDULED', 'SITE_VISITED', 'NEGOTIATION', 'BOOKING_IN_PROGRESS', 'BOOKED', 'LOST', 'FUTURE_PROSPECT'];
const label = (value: string) => value.split('_').map(word => word[0] + word.slice(1).toLowerCase()).join(' ');

export function LeadsPage() {
  const client = useQueryClient();
  const [open, setOpen] = useState(false); const [search, setSearch] = useState(''); const [status, setStatus] = useState('');
  const [name, setName] = useState(''); const [phone, setPhone] = useState(''); const [email, setEmail] = useState(''); const [source, setSource] = useState('Walk-in'); const [priority, setPriority] = useState('MEDIUM'); const [notice, setNotice] = useState('');
  const query = useQuery({ queryKey: ['leads', search, status], queryFn: async () => ((await api.get<{ data: Lead[] }>('/leads', { params: { search: search || undefined, status: status || undefined } })).data.data) });
  const refresh = () => client.invalidateQueries({ queryKey: ['leads'] });
  const create = useMutation({ mutationFn: () => api.post('/leads', { customerName: name, primaryPhone: phone, email, source, priority }), onSuccess: () => { refresh(); setOpen(false); setName(''); setPhone(''); setEmail(''); setNotice('Lead created successfully.'); }, onError: (error: { response?: { data?: { error?: { message?: string } } } }) => setNotice(error.response?.data?.error?.message ?? 'Could not create lead.') });
  const update = useMutation({ mutationFn: ({ id, nextStatus }: { id: string; nextStatus: string }) => api.patch(`/leads/${id}`, { status: nextStatus }), onSuccess: () => { refresh(); setNotice('Lead status updated.'); }, onError: () => setNotice('Could not update this lead.') });
  const convert = useMutation({ mutationFn: (id: string) => api.post(`/leads/${id}/convert`), onSuccess: () => { refresh(); setNotice('Lead converted to a customer profile.'); }, onError: () => setNotice('Could not convert this lead.') });
  const data = query.data ?? [];
  return <section>
    <p className="text-sm text-slate-500">Workspace / Leads</p>
    <div className="mt-2 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-bold text-navy">Leads</h2><p className="mt-1 text-sm text-slate-600">Search, qualify, update, and convert sales enquiries.</p></div><button onClick={() => setOpen(true)} className="flex items-center gap-2 rounded bg-navy px-4 py-2.5 text-sm text-white"><Plus size={18} />Add lead</button></div>
    {notice && <p className="mt-5 rounded bg-blue-50 p-3 text-sm text-navy">{notice}</p>}
    {open && <form onSubmit={event => { event.preventDefault(); create.mutate(); }} className="mt-6 rounded-lg border bg-white p-6"><div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-medium">Customer name<input required value={name} onChange={event => setName(event.target.value)} className="mt-1 w-full rounded border p-2.5" /></label><label className="text-sm font-medium">Phone<input required value={phone} onChange={event => setPhone(event.target.value)} className="mt-1 w-full rounded border p-2.5" /></label><label className="text-sm font-medium">Email<input type="email" value={email} onChange={event => setEmail(event.target.value)} className="mt-1 w-full rounded border p-2.5" /></label><label className="text-sm font-medium">Source<input required value={source} onChange={event => setSource(event.target.value)} className="mt-1 w-full rounded border p-2.5" /></label><label className="text-sm font-medium">Priority<select value={priority} onChange={event => setPriority(event.target.value)} className="mt-1 w-full rounded border p-2.5">{['LOW', 'MEDIUM', 'HIGH', 'URGENT'].map(value => <option key={value}>{value}</option>)}</select></label></div><div className="mt-5 flex gap-3"><button className="rounded bg-navy px-4 py-2.5 text-sm text-white">{create.isPending ? 'Saving...' : 'Save lead'}</button><button type="button" onClick={() => setOpen(false)} className="rounded border px-4 py-2.5 text-sm">Cancel</button></div></form>}
    <div className="mt-6 overflow-hidden rounded-lg border bg-white"><div className="flex flex-wrap gap-3 border-b p-4"><label className="relative block min-w-64 flex-1"><Search className="absolute left-3 top-3 text-slate-400" size={17} /><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search name, phone or lead ID" className="w-full rounded border p-2 pl-9" /></label><select value={status} onChange={event => setStatus(event.target.value)} className="rounded border px-3 text-sm"><option value="">All statuses</option>{statuses.map(value => <option value={value} key={value}>{label(value)}</option>)}</select></div>
      {query.isLoading ? <p className="p-6">Loading leads...</p> : data.length === 0 ? <div className="p-8 text-center"><Users className="mx-auto text-slate-400" /><p className="mt-3 text-sm text-slate-500">No leads found.</p></div> : <div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-slate-50 text-slate-500"><tr><th className="p-4">Lead</th><th className="p-4">Source</th><th className="p-4">Priority</th><th className="p-4">Status</th><th className="p-4">Actions</th></tr></thead><tbody>{data.map(lead => <tr key={lead.id} className="border-t"><td className="p-4 font-medium">{lead.customerName}<br /><span className="text-xs font-normal text-slate-500">{lead.referenceNumber} · {lead.primaryPhone}</span></td><td className="p-4">{lead.source}</td><td className="p-4">{label(lead.priority)}</td><td className="p-4"><select aria-label={`Status for ${lead.customerName}`} value={lead.status} disabled={update.isPending} onChange={event => update.mutate({ id: lead.id, nextStatus: event.target.value })} className="rounded border bg-white px-2 py-1 text-xs">{statuses.map(value => <option key={value} value={value}>{label(value)}</option>)}</select></td><td className="p-4"><button onClick={() => convert.mutate(lead.id)} disabled={convert.isPending} className="inline-flex items-center gap-1 rounded border border-gold px-2.5 py-1.5 text-xs font-medium text-navy"><CheckCircle2 size={14} />Convert</button></td></tr>)}</tbody></table></div>}</div>
  </section>;
}
