ALTER TYPE "PropertyType" ADD VALUE IF NOT EXISTS 'BHK_1';
ALTER TYPE "PropertyType" ADD VALUE IF NOT EXISTS 'BHK_2';
ALTER TYPE "PropertyType" ADD VALUE IF NOT EXISTS 'BHK_3';
ALTER TYPE "PropertyType" ADD VALUE IF NOT EXISTS 'BHK_4';
